/*
** EPITECH PROJECT, 2025
** G-NWP-400-NCE-4-1-myteams-8
** File description:
** protocole.hpp
*/

#ifndef PROTOCOLE_HPP
#define PROTOCOLE_HPP

    #include <cstdint>
    #include <arpa/inet.h>

#define HEADER_SIZE 6

enum Command : uint16_t {
    CMD_LOGIN = 0x01,
    CMD_LOGOUT = 0x02,
    CMD_USERS = 0x03,
    CMD_USER = 0x04,
    CMD_SEND = 0x05,
    CMD_MESSAGES = 0x06,
    CMD_SUBSCRIBE = 0x07,
    CMD_SUBSCRIBED = 0x08,
    CMD_UNSUBSCRIBE = 0x09,
    CMD_USE = 0x0A,
    CMD_CREATE  = 0x0B,
    CMD_LIST = 0x0C,
    CMD_INFO = 0x0D,
};

enum Response : uint16_t {
    RES_LOGIN_OK = 0x10,
    RES_LOGOUT_OK = 0x11,
    RES_USERS_LIST = 0x12,
    RES_USER_INFO = 0x13,
    RES_SEND_OK = 0x14,
    RES_MESSAGES_LIST = 0x15,
    RES_SUBSCRIBE_OK = 0x16,
    RES_SUBSCRIBED_TEAMS = 0x17,
    RES_SUBSCRIBED_USERS = 0x18,
    RES_UNSUBSCRIBE_OK = 0x19,
    RES_TEAM_CREATED = 0x1A,
    RES_CHANNEL_CREATED = 0x1B,
    RES_THREAD_CREATED = 0x1C,
    RES_REPLY_CREATED = 0x1D,
    RES_LIST_TEAMS = 0x1E,
    RES_LIST_CHANNELS = 0x1F,
    RES_LIST_THREADS = 0x20,
    RES_LIST_REPLIES = 0x21,
    RES_TEAM_INFO = 0x22,
    RES_CHANNEL_INFO = 0x23,
    RES_THREAD_INFO = 0x24,
    RES_USER_DETAILS = 0x25,
};

enum Error : uint16_t {
    ERR_UNAUTHORIZED = 0xE0,
    ERR_UNKNOWN_TEAM = 0xE1,
    ERR_UNKNOWN_CHANNEL = 0xE2,
    ERR_UNKNOWN_THREAD = 0xE3,
    ERR_UNKNOWN_USER = 0xE4,
    ERR_ALREADY_EXISTS = 0xE5,
    ERR_NOT_SUBSCRIBED = 0xE6,
    ERR_INVALID_COMMAND = 0xE7,
};

enum Event : uint16_t {
    EVT_MESSAGE_RECEIVED = 0xF0,
    EVT_TEAM_CREATED = 0xF1,
    EVT_CHANNEL_CREATED = 0xF2,
    EVT_THREAD_CREATED = 0xF3,
    EVT_REPLY_CREATED = 0xF4,
    EVT_USER_LOGGED_IN = 0xF5,
    EVT_USER_LOGGED_OUT = 0xF6,
};

enum UseLevel : uint8_t {
    USE_NONE = 0x00,
    USE_TEAM = 0x01,
    USE_CHANNEL = 0x02,
    USE_THREAD = 0x03,
};

#endif